export const genreColors: { [key: string]: string } = {
    "Health Risk Assessment": "#FFD1DC",
    "Finite Mathematics": "#FFCCB6",
    "Subjects & Themes": "#C1A3FF",
    "Cruises": "#FFB7CE",
    "Torts": "#A0D8EF",
    "Salads": "#B2A4E4",
    "Polar Regions": "#A8E6CF",
    "Maturing": "#FFDDC1",
    "Bread": "#FF9AA2",
    "Natural Foods": "#C2B2DA",
    "Orchids": "#FFD1DC",
    "General Practice": "#FFCCB6",
    "Kitchenware": "#C1A3FF",
    "Pictorials": "#FFB7CE",
    "American": "#A0D8EF",
    "Museums": "#B2A4E4",
    "Geriatrics": "#A8E6CF",
    "Agriculture": "#FFDDC1",
    "Self-Hypnosis": "#FF9AA2",
    "True Crime": "#C2B2DA",
    "Gender Studies": "#FFD1DC",
    "Farm Animals": "#FFCCB6",
    "Monologues & Scenes": "#C1A3FF",
    "Serial Killers": "#FFB7CE",
    "Organizations & Institutions": "#A0D8EF",
    "Creative Ability": "#B2A4E4",
    "Radio": "#A8E6CF",
    "Ships & Shipbuilding": "#FFDDC1",
    "Technology": "#FF9AA2",
    "Ethnic & Regional": "#C2B2DA",
    "Thai": "#FFD1DC",
    "Interactive & Multimedia": "#FFCCB6",
    "Individual Director": "#C1A3FF",
    "Trade & Tariffs": "#FFB7CE",
    "Word Games": "#A0D8EF",
    "Rheumatology": "#B2A4E4",
    "Etiquette": "#A8E6CF",
    "Health Policy": "#FFDDC1",
    "Biblical Meditations": "#FF9AA2",
    "Medical": "#C2B2DA",
    "Criminology": "#FFD1DC",
    "Self-Esteem & Self-Reliance": "#FFCCB6",
    "Career Development": "#C1A3FF",
    "Fiction Writing": "#FFB7CE",
    "East North Central (IL": "#A0D8EF",
    "Viruses & Malware": "#B2A4E4",
    "Russia & the Former Soviet Union": "#A8E6CF",
    "Social Science": "#FFDDC1",
    "Bibles": "#FF9AA2",
    "Crisis Management": "#C2B2DA",
    "Screenwriting": "#FFD1DC",
    "Imagination & Play": "#FFCCB6",
    "Genetics & Genomics": "#C1A3FF",
    "Alcoholism": "#FFB7CE",
    "Spiritualism": "#A0D8EF",
    "Medical History & Records": "#B2A4E4",
    "Dance": "#A8E6CF",
    "Language Arts": "#FFDDC1",
    "Wine & Spirits": "#FF9AA2",
    "Ecosystems & Habitats": "#C2B2DA",
    "Drawing & Presentation": "#FFD1DC",
    "Food Science": "#FFCCB6",
    "Remote Sensing & Geographic Information Systems": "#C1A3FF",
    "Transcendentalism": "#FFB7CE",
    "Gardening": "#A0D8EF",
    "Runaways": "#B2A4E4",
    "Cars & Trucks": "#A8E6CF",
    "Soups & Stews": "#FFDDC1",
    "Museum Studies": "#FF9AA2",
    "Musculoskeletal": "#C2B2DA",
    "Resorts & Spas": "#FFD1DC",
    "Amphibians & Terrariums": "#FFCCB6",
    "Sales & Selling": "#C1A3FF",
    "Action & Adventure": "#FFB7CE",
    "Mechanical": "#A0D8EF",
    "Semiotics & Theory": "#B2A4E4",
    "Wills": "#A8E6CF",
    "Bowling": "#FFDDC1",
    "Holidays & Celebrations": "#FF9AA2",
    "Alternative & Complementary Medicine": "#C2B2DA",
    "Conducting": "#FFD1DC",
    "Czech": "#FFCCB6",
    "Discoveries": "#C1A3FF",
    "Green Business": "#FFB7CE",
    "Television & Video": "#A0D8EF",
    "Military Science": "#B2A4E4",
    "Clothing & Dress": "#A8E6CF",
    "School Age": "#FFDDC1",
    "Transportation": "#FF9AA2",
    "Juvenile Fiction": "#C2B2DA",
    "Biographical": "#FFD1DC",
    "Birds": "#FFCCB6",
    "Atlantic Provinces (NB": "#C1A3FF",
    "Hamsters": "#FFB7CE",
    "United States": "#A0D8EF",
    "Pets": "#B2A4E4",
    "Business Law": "#A8E6CF",
    "City & Town Life": "#FFDDC1",
    "Middle Atlantic (DC": "#FF9AA2",
    "Technology & Engineering": "#C2B2DA",
    "Biblical Biography": "#FFD1DC",
    "Multi-Language Dictionaries": "#FFCCB6",
    "Geometry": "#C1A3FF",
    "Techniques": "#FFB7CE",
    "Comedy": "#A0D8EF",
    "South": "#B2A4E4",
    "Hinduism": "#A8E6CF",
    "Fruit": "#FFDDC1",
    "Unexplained Phenomena": "#FF9AA2",
    "Catechisms": "#C2B2DA",
    "Storage & Retrieval": "#FFD1DC",
    "Royalty": "#FFCCB6",
    "Herbal Medications": "#C1A3FF",
    "Film & Video": "#FFB7CE",
    "Adoption & Fostering": "#A0D8EF",
    "Terrorism": "#B2A4E4",
    "Public Affairs & Administration": "#A8E6CF",
    "Earth Sciences": "#FFDDC1",
    "Multiple Translations": "#FF9AA2",
    "AR": "#C2B2DA",
    "Test Preparation & Review": "#FFD1DC",
    "Hunting": "#FFCCB6",
    "Handbooks": "#C1A3FF",
    "Fundamentalism": "#FFB7CE",
    "Gambling": "#A0D8EF",
    "Motivational": "#B2A4E4",
    "Library & Information Science": "#A8E6CF",
    "Public Speaking": "#FFDDC1",
    "Men's Studies": "#FF9AA2",
    "Worship & Liturgy": "#C2B2DA",
    "Internet": "#FFD1DC",
    "King James Version": "#FFCCB6",
    "California Style": "#C1A3FF",
    "Running & Jogging": "#FFB7CE",
    "Crocheting": "#A0D8EF",
    "Journalism": "#B2A4E4",
    "National": "#A8E6CF",
    "Spirituality": "#FFDDC1",
    "Dictionaries": "#FF9AA2",
    "Sleep": "#C2B2DA",
    "Birthdays": "#FFD1DC",
    "Youth": "#FFCCB6",
    "Film": "#C1A3FF",
    "Bartending": "#FFB7CE",
    "Budgeting": "#A0D8EF",
    "Human Sexuality": "#B2A4E4",
    "Language Arts & Disciplines": "#A8E6CF",
    "Biophysics": "#FFDDC1",
    "Language Study": "#FF9AA2",
    "Constitutional": "#C2B2DA",
    "Iraq War (2003-2011)": "#FFD1DC",
    "China": "#FFCCB6",
    "Cartooning": "#C1A3FF",
    "Buildings": "#FFB7CE",
    "Jewelry": "#A0D8EF",
    "Pascal": "#B2A4E4",
    "Dinosaurs & Prehistoric Creatures": "#A8E6CF",
    "Personality Disorders": "#FFDDC1",
    "Textiles & Costume": "#FF9AA2",
    "Children with Special Needs": "#C2B2DA",
    "Raw Food": "#FFD1DC",
    "Geese": "#FFCCB6",
    "Dolls & Puppets": "#C1A3FF",
    "Biblical Criticism & Interpretation": "#FFB7CE",
    "Philanthropy & Charity": "#A0D8EF",
    "Educational Policy & Reform": "#B2A4E4",
    "etc.)": "#A8E6CF",
    "NM": "#FFDDC1",
    "Cookery for One": "#FF9AA2",
    "Mobile & Wireless Communications": "#C2B2DA",
    "Business Communication": "#FFD1DC",
    "Scrapbooking": "#FFCCB6",
    "Songbooks": "#C1A3FF",
    "Paranormal": "#FFB7CE",
    "Educators": "#A0D8EF",
    "Calculus": "#B2A4E4",
    "Shintoism": "#A8E6CF",
    "Communicative Disorders": "#FFDDC1",
    "Regional Planning": "#FF9AA2",
    "Alternative Therapies": "#C2B2DA",
    "Study Skills": "#FFD1DC",
    "Jesus": "#FFCCB6",
    "BC)": "#C1A3FF",
    "Physical Education": "#FFB7CE",
    "Republic of South Africa": "#A0D8EF",
    "Study & Teaching": "#B2A4E4",
    "Earthquakes & Volcanoes": "#A8E6CF",
    "Fantasy Sports": "#FFDDC1",
    "HTML": "#FF9AA2",
    "Popular Culture": "#C2B2DA",
    "Decision-Making & Problem Solving": "#FFD1DC",
    "Creativity": "#FFCCB6",
    "Optics & Light": "#C1A3FF",
    "Mystery & Detective": "#FFB7CE",
    "Thesauri": "#A0D8EF",
    "Bears": "#B2A4E4",
    "Success": "#A8E6CF",
    "Algebra": "#FFDDC1",
    "Feminism & Feminist Theory": "#FF9AA2",
    "Religion & Science": "#C2B2DA",
    "God's Word": "#FFD1DC",
    "Dictionaries & Terminology": "#FFCCB6",
    "Photographers": "#C1A3FF",
    "Exercise": "#FFB7CE",
    "Laboratory Medicine": "#A0D8EF",
    "Public Contract": "#B2A4E4",
    "Beer": "#A8E6CF",
    "International Relations": "#FFDDC1",
    "Sports & Recreation": "#FF9AA2",
    "Windows Server": "#C2B2DA",
    "Divination": "#FFD1DC",
    "Humanism": "#FFCCB6",
    "Methodist": "#C1A3FF",
    "Archaeology": "#FFB7CE",
    "Islam": "#A0D8EF",
    "Thrillers": "#B2A4E4",
    "Intranets & Extranets": "#A8E6CF",
    "Saints & Sainthood": "#FFDDC1",
    "Industrial": "#FF9AA2",
    "Outdoor & Recreational Areas": "#C2B2DA",
    "Mathematical Analysis": "#FFD1DC",
    "Dating & Relationships": "#FFCCB6",
    "Colonial Period (1600-1775)": "#C1A3FF",
    "Non-Alcoholic": "#FFB7CE",
    "Industrial Management": "#A0D8EF",
    "BASIC": "#B2A4E4",
    "Respiratory": "#A8E6CF",
    "Pension Law": "#FFDDC1",
    "Democracy": "#FF9AA2",
    "Cats": "#C2B2DA",
    "Dating & Sex": "#FFD1DC",
    "Nationalism & Patriotism": "#FFCCB6",
    "Systematic": "#C1A3FF",
    "Fiction": "#FFB7CE",
    "Greek": "#A0D8EF",
    "Pathology": "#B2A4E4",
    "Coaching": "#A8E6CF",
    "Seafood": "#FFDDC1",
    "Cults": "#FF9AA2",
    "Corporate Finance": "#C2B2DA",
    "Individual Artists": "#FFD1DC",
    "Communication Studies": "#FFCCB6",
    "JavaScript": "#C1A3FF",
    "New Experience": "#FFB7CE",
    "Latin America": "#A0D8EF",
    "SD)": "#B2A4E4",
    "Administration": "#A8E6CF",
    "Happiness": "#FFDDC1",
    "Turtles": "#FF9AA2",
    "Gazetteers & Maps": "#C2B2DA",
    "Grief": "#FFD1DC",
    "Fertility & Infertility": "#FFCCB6",
    "Preaching": "#C1A3FF",
    "Customs & Traditions": "#FFB7CE",
    "Dogs": "#A0D8EF",
    "Audio": "#B2A4E4",
    "Social Issues": "#A8E6CF",
    "Alligators & Crocodiles": "#FFDDC1",
    "Martial Arts": "#FF9AA2",
    "Contemporary (1945-)": "#C2B2DA",
    "Social Theory": "#FFD1DC",
    "Alzheimer's & Dementia": "#FFCCB6",
    "Weight Control": "#C1A3FF",
    "Ice Skating": "#FFB7CE",
    "Games": "#A0D8EF",
    "NS": "#B2A4E4",
    "Project Management": "#A8E6CF",
    "Media Studies": "#FFDDC1",
    "Irish": "#FF9AA2",
    "IL": "#C2B2DA",
    "Piloting & Flight Instruction": "#FFD1DC",
    "Outdoor Skills": "#FFCCB6",
    "Environment": "#C1A3FF",
    "Literary Figures": "#FFB7CE",
    "Teenagers": "#A0D8EF",
    "Real Estate": "#B2A4E4",
    "Boxing": "#A8E6CF",
    "Vocabulary & Spelling": "#FFDDC1",
    "Volleyball": "#FF9AA2",
    "Northwestern States": "#C2B2DA",
    "Programming Languages": "#FFD1DC",
    "Japanese Gardens": "#FFCCB6",
    "Email Clients": "#C1A3FF",
    "Metaphysics": "#FFB7CE",
    "Persian Gulf War (1991)": "#A0D8EF",
    "Printmaking": "#B2A4E4",
    "MD": "#A8E6CF",
    "Bibliographies & Indexes": "#FFDDC1",
    "Science": "#FF9AA2",
    "Regency": "#C2B2DA",
    "Wine": "#FFD1DC",
    "Job Hunting": "#FFCCB6",
    "Hiking": "#C1A3FF",
    "Lace & Tatting": "#FFB7CE",
    "Crafts & Hobbies": "#A0D8EF",
    "Performing Arts": "#B2A4E4",
    "Patchwork": "#A8E6CF",
    "English": "#FFDDC1",
    "Healthy Living": "#FF9AA2",
    "Fishing": "#C2B2DA",
    "Telemarketing": "#FFD1DC",
    "Christmas & Advent": "#FFCCB6",
    "Piano & Keyboard": "#C1A3FF",
    "Readers": "#FFB7CE",
    "Crosswords": "#A0D8EF",
    "Dairy": "#B2A4E4",
    "Board": "#A8E6CF",
    "Islamic Studies": "#FFDDC1",
    "Ethics": "#FF9AA2",
    "House & Home": "#C2B2DA",
    "C++": "#FFD1DC",
    "Hospitality": "#FFCCB6",
    "Manga": "#C1A3FF",
    "Secondary": "#FFB7CE",
    "Greek & Roman": "#A0D8EF",
    "Substance Abuse & Addictions": "#B2A4E4",
    "Knowledge Capital": "#A8E6CF",
    "South (AL": "#FFDDC1",
    "Eastern": "#FF9AA2",
    "Beadwork": "#C2B2DA",
    "Feng Shui": "#FFD1DC",
    "Machinery & Tools": "#FFCCB6",
    "Brunch & Tea Time": "#C1A3FF",
    "Lutheran": "#FFB7CE",
    "Linux": "#A0D8EF",
    "Juices & Smoothies": "#B2A4E4",
    "Beverages": "#A8E6CF",
    "Computers & Technology": "#FFDDC1",
    "Garden Design": "#FF9AA2",
    "Carpentry": "#C2B2DA",
    "Oral & Maxillofacial": "#FFD1DC",
    "Arms Control": "#FFCCB6",
    "Asian": "#C1A3FF",
    "Precognition": "#FFB7CE",
    "Weddings": "#A0D8EF",
    "Institutions & Organizations": "#B2A4E4",
    "Topic": "#A8E6CF",
    "Commerce": "#FFDDC1",
    "New American Bible": "#FF9AA2",
    "Human Anatomy & Physiology": "#C2B2DA",
    "Quilts & Quilting": "#FFD1DC",
    "Baltic States": "#FFCCB6",
    "Public": "#C1A3FF",
    "Communism": "#FFB7CE",
    "Neurology": "#A0D8EF",
    "Central America": "#B2A4E4",
    "West Indies)": "#A8E6CF",
    "Internships": "#FFDDC1",
    "Channeling & Mediumship": "#FF9AA2",
    "Cakes": "#C2B2DA",
    "Critical & Intensive Care": "#FFD1DC",
    "Science Fiction & Fantasy": "#FFCCB6",
    "Fashion": "#C1A3FF",
    "Biology": "#FFB7CE",
    "Higher": "#A0D8EF",
    "Canadian": "#B2A4E4",
    "Koran & Sacred Writings": "#A8E6CF",
    "Adaptations": "#FFDDC1",
    "Civics & Citizenship": "#FF9AA2",
    "Adolescent": "#C2B2DA",
    "Management Science": "#FFD1DC",
    "Biblical Commentary": "#FFCCB6",
    "Gothic & Romance": "#C1A3FF",
    "Alcoholic": "#FFB7CE",
    "Exhibitions": "#A0D8EF",
    "Industries": "#B2A4E4",
    "Sociology of Religion": "#A8E6CF",
    "Critical Care": "#FFDDC1",
    "Homelessness & Poverty": "#FF9AA2",
    "Evaluation & Assessment": "#C2B2DA",
    "Human Services": "#FFD1DC",
    "History & Culture": "#FFCCB6",
    "Animals": "#C1A3FF",
    "Court Rules": "#FFB7CE",
    "Breeds": "#A0D8EF",
    "Flowers": "#B2A4E4",
    "Physiological Psychology": "#A8E6CF",
    "Common English Bible": "#FFDDC1",
    "Winter Sports": "#FF9AA2",
    "Mermaids": "#C2B2DA",
    "Sports Medicine": "#FFD1DC",
    "People & Places": "#FFCCB6",
    "Canning & Preserving": "#C1A3FF",
    "Ghost Stories": "#FFB7CE",
    "Dark Fantasy": "#A0D8EF",
    "Boats": "#B2A4E4",
    "Aeronautics": "#A8E6CF",
    "Organizational Behavior": "#FFDDC1",
    "Military": "#FF9AA2",
    "History": "#C2B2DA",
    "Animal Husbandry": "#FFD1DC",
    "Pre-Calculus": "#FFCCB6",
    "Abuse": "#C1A3FF",
    "Political Economy": "#FFB7CE",
    "Bridges": "#A0D8EF",
    "Criminal Procedure": "#B2A4E4",
    "Forecasting": "#A8E6CF",
    "Biblical Stories & Studies": "#FFDDC1",
    "Biochemistry": "#FF9AA2",
    "Industrial Engineering": "#C2B2DA",
    "New Testament & Portions": "#FFD1DC",
    "Cognitive Psychology & Cognition": "#FFCCB6",
    "Alternative Medicine": "#C1A3FF",
    "Counseling & Recovery": "#FFB7CE",
    "Equipment & Supplies": "#A0D8EF",
    "Economic Development": "#B2A4E4",
    "Urban & Regional": "#A8E6CF",
    "Animal Rights": "#FFDDC1",
    "Personality": "#FF9AA2",
    "Angels & Spirit Guides": "#C2B2DA",
    "Space Opera": "#FFD1DC",
    "Book Notes": "#FFCCB6",
    "Hardware": "#C1A3FF",
    "Astronautics & Space Science": "#FFB7CE",
    "Management": "#A0D8EF",
    "Advanced Placement": "#B2A4E4",
    "UT": "#A8E6CF",
    "Shakespeare": "#FFDDC1",
    "Folk & Traditional": "#FF9AA2",
    "Christology": "#C2B2DA",
    "Music": "#FFD1DC",
    "Management & Leadership": "#FFCCB6",
    "Broadband": "#C1A3FF",
    "Preschool & Kindergarten": "#FFB7CE",
    "Allied Health Services": "#A0D8EF",
    "Quotations": "#B2A4E4",
    "New King James Version": "#A8E6CF",
    "Macrobiotics": "#FFDDC1",
    "Middle Eastern": "#FF9AA2",
    "Ethical & Legal Issues": "#C2B2DA",
    "Coins": "#FFCCB6",
    "Children's Studies": "#C1A3FF",
    "Spiders": "#FFB7CE",
    "Quick & Easy": "#A0D8EF",
    "Women": "#B2A4E4",
    "Faith": "#A8E6CF",
    "Environmental Policy": "#FFDDC1",
    "Social Psychology": "#FF9AA2",
    "Christian Education": "#C2B2DA",
    "Historical Geography": "#FFD1DC",
    "Sermons": "#FFCCB6",
    "Illnesses & Injuries": "#C1A3FF",
    "Digital": "#FFB7CE",
    "Family": "#A0D8EF",
    "East South Central (AL": "#B2A4E4",
    "Myths": "#A8E6CF",
    "Judicial Branch": "#FFDDC1",
    "Ecuador & Galapagos Islands": "#FF9AA2",
    "Healing": "#C2B2DA",
    "Egypt": "#FFD1DC",
    "Death": "#FFCCB6",
    "SD": "#C1A3FF",
    "Speech & Pronunciation": "#FFB7CE",
    "Women's Interests": "#A0D8EF",
    "Primates": "#B2A4E4",
    "Oncology": "#A8E6CF",
    "Corporate": "#FFDDC1",
    "Word Lists": "#FF9AA2",
    "NV": "#C2B2DA",
    "Africa": "#FFD1DC",
    "Tablesetting": "#FFCCB6",
    "UFOs & Extraterrestrials": "#C1A3FF",
    "Information Technology": "#FFB7CE",
    "Anesthesiology": "#A0D8EF",
    "Linguistics": "#B2A4E4",
    "Social Networking": "#A8E6CF",
    "Wok": "#FFDDC1",
    "Publishers": "#FF9AA2",
    "New Testament": "#C2B2DA",
    "Rural": "#FFD1DC",
    "European": "#C1A3FF",
    "Appliances & Supplies": "#FFB7CE",
    "Women's Health": "#A0D8EF",
    "Clinical Psychology": "#B2A4E4",
    "Physician & Patient": "#A8E6CF",
    "Rivers": "#FFDDC1",
    "Meteorology & Climatology": "#FF9AA2",
    "Zoology": "#C2B2DA",
    "Celebrity": "#FFD1DC",
    "Ducks": "#FFCCB6",
    "Bed & Breakfast": "#C1A3FF",
    "Family & General Practice": "#FFB7CE",
    "World": "#A0D8EF",
    "Technological": "#B2A4E4",
    "Information Management": "#A8E6CF",
    "Book Printing & Binding": "#FFDDC1",
    "Diseases": "#FF9AA2",
    "Sculpture": "#C2B2DA",
    "Religion": "#FFD1DC",
    "Direction & Production": "#FFCCB6",
    "Social Scientists & Psychologists": "#C1A3FF",
    "PCs": "#FFB7CE",
    "Memory Improvement": "#A0D8EF",
    "Russian": "#B2A4E4",
    "Asian American Studies": "#A8E6CF",
    "Cycling": "#FFDDC1",
    "Golf": "#FF9AA2",
    "Monkeys": "#C2B2DA",
    "Limericks & Verse": "#FFD1DC",
    "E-Commerce": "#FFCCB6",
    "Development": "#C1A3FF",
    "Child Abuse": "#FFB7CE",
    "Pharmacology": "#A0D8EF",
    "Distribution": "#B2A4E4",
    "Developmental & Intellectual Disabilities": "#A8E6CF",
    "Paul's Letters": "#FFDDC1",
    "Reggae": "#FF9AA2",
    "Experiments & Projects": "#C2B2DA",
    "Special Education": "#FFD1DC",
    "Erotica": "#FFCCB6",
    "Toilet Training": "#C1A3FF",
    "Toys": "#FFB7CE",
    "Cultural & Social": "#A0D8EF",
    "Classical": "#B2A4E4",
    "Operating Systems": "#A8E6CF",
    "Health": "#FFDDC1",
    "Mood Disorders": "#FF9AA2",
    "Exploration & Discovery": "#C2B2DA",
    "Politics & State": "#FFD1DC",
    "Maps & Road Atlases": "#FFCCB6",
    "Places": "#C1A3FF",
    "Questions & Answers": "#FFB7CE",
    "VT)": "#A0D8EF",
    "Forensic Science": "#B2A4E4",
    "Right to Die": "#A8E6CF",
    "Editing & Proofreading": "#FFDDC1",
    "Econometrics": "#FF9AA2",
    "Art": "#C2B2DA",
    "Negotiating": "#FFD1DC",
    "Labor & Industrial Relations": "#FFCCB6",
    "Environmental Science & Ecosystems": "#C1A3FF",
    "History & Criticism": "#FFB7CE",
    "Yoga": "#A0D8EF",
    "Seashells": "#B2A4E4",
    "Love & Romance": "#A8E6CF",
    "Other Translations": "#FFDDC1",
    "Search Engines": "#FF9AA2",
    "Enterprise Applications": "#C2B2DA",
    "Civil War Period (1850-1877)": "#FFD1DC",
    "Women Sleuths": "#FFCCB6",
    "Investments & Securities": "#C1A3FF",
    "General": "#FFB7CE",
    "Computer Graphics": "#A0D8EF",
    "Cultural Heritage": "#B2A4E4",
    "Women's Issues": "#A8E6CF",
    "Experimental Methods": "#FFDDC1",
    "Love & Erotica": "#FF9AA2",
    "Stewardship & Giving": "#C2B2DA",
    "ID": "#FFD1DC",
    "Relationships": "#FFCCB6",
    "Military & Wars": "#C1A3FF",
    "Law & Crime": "#FFB7CE",
    "Extreme Sports": "#A0D8EF",
    "Astrophysics": "#B2A4E4",
    "International Security": "#A8E6CF",
    "Physical Impairments": "#FFDDC1",
    "Fundamentals & Skills": "#FF9AA2",
    "Anecdotes & Quotations": "#C2B2DA",
    "Semantics": "#FFD1DC",
    "Life Sciences": "#FFCCB6",
    "Hematology": "#C1A3FF",
    "African American": "#FFB7CE",
    "Careers": "#A0D8EF",
    "Composition & Creative Writing": "#B2A4E4",
    "Holistic Medicine": "#A8E6CF",
    "Sagas": "#FFDDC1",
    "Bookkeeping": "#FF9AA2",
    "GA": "#C2B2DA",
    "Wood Toys": "#FFD1DC",
    "Coffee & Tea": "#FFCCB6",
    "Client-Server Computing": "#C1A3FF",
    "Intellectual Property": "#FFB7CE",
    "Magick Studies": "#A0D8EF",
    "Telecommunications": "#B2A4E4",
    "Taoist": "#A8E6CF",
    "Activity Books": "#FFDDC1",
    "Editors": "#FF9AA2",
    "Marriage & Divorce": "#C2B2DA",
    "Probability & Statistics": "#FFD1DC",
    "Movements": "#FFCCB6",
    "Aerial": "#C1A3FF",
    "Metal Work": "#FFB7CE",
    "Rice & Grains": "#A0D8EF",
    "Online Services": "#B2A4E4",
    "Gothic": "#A8E6CF",
    "Arts & Humanities": "#FFDDC1",
    "Bodybuilding & Weight Training": "#FF9AA2",
    "Liability": "#C2B2DA",
    "Meat": "#FFD1DC",
    "Easter & Lent": "#FFCCB6",
    "Differential": "#C1A3FF",
    "Germany": "#FFB7CE",
    "NL": "#A0D8EF",
    "Meditations": "#B2A4E4",
    "Folk Tales": "#A8E6CF",
    "Middle Atlantic (NJ": "#FFDDC1",
    "Health & Healing": "#FF9AA2",
    "Landscapes & Seascapes": "#C2B2DA",
    "State": "#FFD1DC",
    "Guinea Pigs": "#FFCCB6",
    "Hispanic American": "#C1A3FF",
    "Dough": "#FFB7CE",
    "Slavery": "#A0D8EF",
    "Scandinavia (Finland": "#B2A4E4",
    "Business Development": "#A8E6CF",
    "Soccer": "#FFDDC1",
    "Christianity": "#FF9AA2",
    "Small Animal": "#C2B2DA",
    "Taxation": "#FFD1DC",
    "Multigenerational": "#FFCCB6",
    "Criminals & Outlaws": "#C1A3FF",
    "Magic": "#FFB7CE",
    "Devotional & Prayer": "#A0D8EF",
    "Family Law": "#B2A4E4",
    "Country & Ethnic": "#A8E6CF",
    "Science Fiction": "#FFDDC1",
    "Number Systems": "#C2B2DA",
    "Men's Issues": "#FFD1DC",
    "Fashion & Beauty": "#FFCCB6",
    "SC": "#C1A3FF",
    "Ancient": "#FFB7CE",
    "Urology": "#A0D8EF",
    "Skills": "#B2A4E4",
    "C": "#A8E6CF",
    "Jewish & Kosher": "#FF9AA2",
    "Antique & Classic": "#C2B2DA",
    "Political Advocacy": "#FFD1DC",
    "Sociolinguistics": "#FFCCB6",
    "Chinese": "#C1A3FF",
    "Museum Administration & Museology": "#FFB7CE",
    "Lifestyles": "#A0D8EF",
    "Popular": "#B2A4E4",
    "Adoption": "#A8E6CF",
    "Superheroes": "#FFDDC1",
    "Global Warming & Climate Change": "#FF9AA2",
    "Mexican": "#C2B2DA",
    "Body Art & Tattooing": "#FFD1DC",
    "Violence in Society": "#FFCCB6",
    "Vietnam War": "#C1A3FF",
    "OH": "#FFB7CE",
    "Training": "#A0D8EF",
    "Office Management": "#B2A4E4",
    "Geology": "#A8E6CF",
    "Databases": "#FFDDC1",
    "Compulsive Behavior": "#FF9AA2",
    "Wildlife": "#C2B2DA",
    "Affirmations": "#FFD1DC",
    "Marine Biology": "#FFCCB6",
    "Classical & Ballet": "#C1A3FF",
    "Individual Photographers": "#FFB7CE",
    "Anthologies": "#A0D8EF",
    "Gastroenterology": "#B2A4E4",
    "Automotive": "#A8E6CF",
    "Buddhism": "#FFDDC1",
    "Ancient Civilizations": "#FF9AA2",
    "Traditional British": "#C2B2DA",
    "Patent": "#FFD1DC",
    "Technical Writing": "#FFCCB6",
    "Pastoral Resources": "#C1A3FF",
    "Models": "#FFB7CE",
    "Customer Relations": "#A0D8EF",
    "Genres & Styles": "#B2A4E4",
    "Playwriting": "#A8E6CF",
    "Nuclear Warfare": "#FFDDC1",
    "Physiology": "#FF9AA2",
    "Electricity & Electronics": "#C2B2DA",
    "Windows Workstation": "#FFD1DC",
    "Birds & Birdwatching": "#FFCCB6",
    "Tests (Other)": "#C1A3FF",
    "Currency & Medals": "#FFB7CE",
    "Economic Policy": "#A0D8EF",
    "Trigonometry": "#B2A4E4",
    "Maintenance & Repair": "#A8E6CF",
    "Customs": "#FFDDC1",
    "Acting & Auditioning": "#FF9AA2",
    "Parent Participation": "#C2B2DA",
    "Public Health": "#FFD1DC",
    "Travel & Tourism": "#FFCCB6",
    "Sculpture & Installation": "#C1A3FF",
    "Social History": "#FFB7CE",
    "Chapter Books": "#A0D8EF",
    "Media Tie-In": "#B2A4E4",
    "Middle East": "#A8E6CF",
    "Patriotic Holidays": "#FFDDC1",
    "Fairy Tales & Folklore": "#FF9AA2",
    "Pastel Drawing": "#C2B2DA",
    "Southwest": "#FFD1DC",
    "Christian": "#FFCCB6",
    "Physics": "#C1A3FF",
    "Squirrels": "#FFB7CE",
    "Substance Abuse": "#A0D8EF",
    "Suicide": "#B2A4E4",
    "Insects": "#A8E6CF",
    "Oral Health": "#FFDDC1",
    "Soteriology": "#FF9AA2",
    "Espionage": "#C2B2DA",
    "Western Provinces (AB": "#FFD1DC",
    "Hanukkah": "#FFCCB6",
    "Adult Children of Substance Abusers": "#C1A3FF",
    "Glass & Glassware": "#FFB7CE",
    "Data Transmission Systems": "#A0D8EF",
    "Style Manuals": "#B2A4E4",
    "Industrial Technology": "#A8E6CF",
    "Legends": "#FFDDC1",
    "Kayaking": "#FF9AA2",
    "Prayer & Spiritual": "#C2B2DA",
    "Crime & Mystery": "#FFD1DC",
    "Business Writing": "#FFCCB6",
    "Caribbean & West Indian": "#C1A3FF",
    "Coming of Age": "#FFB7CE",
    "Senses & Sensation": "#A0D8EF",
    "Christian Ministry": "#B2A4E4",
    "Woodwinds": "#A8E6CF",
    "Textile & Costume": "#FFDDC1",
    "Conceptual": "#FF9AA2",
    "Antiques & Collectibles": "#C2B2DA",
    "Holocaust": "#FFD1DC",
    "Wizards & Witches": "#FFCCB6",
    "Supernatural": "#C1A3FF",
    "Commentary & Opinion": "#FFB7CE",
    "New International Version": "#A0D8EF",
    "Analytic": "#B2A4E4",
    "Bipolar Disorder": "#A8E6CF",
    "Humorous Stories": "#FFDDC1",
    "Power Resources": "#FF9AA2",
    "Historiography": "#C2B2DA",
    "Psychoanalysis": "#FFD1DC",
    "Immune & Autoimmune": "#FFCCB6",
    "Penology": "#C1A3FF",
    "Government & Business": "#FFB7CE",
    "Eschatology": "#A0D8EF",
    "Contemporary Women": "#B2A4E4",
    "Drug Guides": "#A8E6CF",
    "Jurisprudence": "#FFDDC1",
    "Lesbian": "#FF9AA2",
    "Treaties": "#C2B2DA",
    "Social Themes": "#FFD1DC",
    "Dynamics": "#FFCCB6",
    "Inventions": "#C1A3FF",
    "Beginner": "#FFB7CE",
    "Ecology": "#A0D8EF",
    "Country & Bluegrass": "#B2A4E4",
    "Design": "#A8E6CF",
    "Western": "#FFDDC1",
    "Social Aspects": "#FF9AA2",
    "Ships & Underwater Craft": "#C2B2DA",
    "Kabbalah & Mysticism": "#FFD1DC",
    "Mysticism": "#FFCCB6",
    "Volunteer Work": "#C1A3FF",
    "WV)": "#FFB7CE",
    "Money": "#A0D8EF",
    "Afghan War (2001-)": "#B2A4E4",
    "Words": "#A8E6CF",
    "Southern States": "#FFDDC1",
    "Aviation": "#FF9AA2",
    "Northeast": "#C2B2DA",
    "Special Needs": "#FFD1DC",
    "Catalogs": "#FFCCB6",
    "Sustainable Living": "#C1A3FF",
    "Operations Research": "#FFB7CE",
    "Food Content Guides": "#A0D8EF",
    "Energy Policy": "#B2A4E4",
    "Sexuality & Gender Studies": "#A8E6CF",
    "Vegetables": "#FFDDC1",
    "Business & Economics": "#FF9AA2",
    "Daily Activities": "#C2B2DA",
    "Strangers": "#FFD1DC",
    "Morocco": "#FFCCB6",
    "College Entrance": "#C1A3FF",
    "Economics": "#FFB7CE",
    "Mineralogy": "#A0D8EF",
    "Women & Relationships": "#B2A4E4",
    "TN)": "#A8E6CF",
    "Allergies": "#FFDDC1",
    "SQL": "#FF9AA2",
    "Energy (Qigong": "#C2B2DA",
    "Internet Marketing": "#FFD1DC",
    "Midwest": "#FFCCB6",
    "Legal Education": "#C1A3FF",
    "Infectious Diseases": "#FFB7CE",
    "Rugs": "#A0D8EF",
    "Europe": "#B2A4E4",
    "Biostatistics": "#A8E6CF",
    "Marine Life": "#FFDDC1",
    "Ice & Figure Skating": "#FF9AA2",
    "State & Local": "#C2B2DA",
    "Game": "#FFD1DC",
    "Canada": "#FFCCB6",
    "Mechanics": "#C1A3FF",
    "Martial Arts & Self-Defense": "#FFB7CE",
    "Professional": "#A0D8EF",
    "Sandwiches": "#B2A4E4",
    "Baby Food": "#A8E6CF",
    "Post-Communism & Socialism": "#FFDDC1",
    "Sea Stories": "#FF9AA2",
    "Professional Development": "#C2B2DA",
    "Midwest (IA": "#FFD1DC",
    "Evidence": "#FFCCB6",
    "Government": "#C1A3FF",
    "Video & Electronic": "#FFB7CE",
    "Gay Studies": "#A0D8EF",
    "Theory": "#B2A4E4",
    "Blended Families": "#A8E6CF",
    "PSAT & NMSQT (National Merit Scholarship Qualifying Test)": "#FFDDC1",
    "Ireland": "#FF9AA2",
    "Vegetarian & Vegan": "#C2B2DA",
    "Japanese": "#FFD1DC",
    "Non-Formal Education": "#FFCCB6",
    "Psychological": "#C1A3FF",
    "New Living Translation": "#FFB7CE",
    "Country Life": "#A0D8EF",
    "Puppets": "#B2A4E4",
    "Humorous": "#A8E6CF",
    "Contracting": "#FFDDC1",
    "Mice": "#FF9AA2",
    "Rationalism": "#C2B2DA",
    "Word & Word Search": "#FFD1DC",
    "Special Interest": "#FFCCB6",
    "TN": "#C1A3FF",
    "Ornamental Plants": "#FFB7CE",
    "Wolves & Coyotes": "#A0D8EF",
    "Anthologies (multiple authors)": "#B2A4E4",
    "Research & Theory": "#A8E6CF",
    "WA)": "#FFDDC1",
    "20th Century": "#FF9AA2",
    "Pizza": "#C2B2DA",
    "Ontario (ON)": "#FFD1DC",
    "Small Business": "#FFCCB6",
    "Musicals": "#C1A3FF",
    "Journalists": "#FFB7CE",
    "Holidays": "#A0D8EF",
    "West South Central (AR": "#B2A4E4",
    "Middle Atlantic States": "#A8E6CF",
    "Biblical Studies": "#FFDDC1",
    "Health Care Delivery": "#FF9AA2",
    "PA)": "#C2B2DA",
    "History & Theory": "#FFD1DC",
    "Discrimination": "#FFCCB6",
    "African": "#C1A3FF",
    "Bible Study Guides": "#FFB7CE",
    "Acoustics & Sound": "#A0D8EF",
    "Children's Literature": "#B2A4E4",
    "Southwestern States": "#A8E6CF",
    "Puzzles": "#FFDDC1",
    "Russian & Former Soviet Union": "#FF9AA2",
    "Mergers & Acquisitions": "#C2B2DA",
    "Computers & Information Technology": "#FFD1DC",
    "Swimming": "#FFCCB6",
    "Comics & Graphic Novels": "#C1A3FF",
    "Hockey": "#FFB7CE",
    "Plants": "#A0D8EF",
    "Natural Resources": "#B2A4E4",
    "Civil Law": "#A8E6CF",
    "Murder": "#FFDDC1",
    "Photography": "#FF9AA2",
    "Typography": "#C2B2DA",
    "Adult & Continuing Education": "#FFD1DC",
    "Assessment & Diagnosis": "#FFCCB6",
    "Americana": "#C1A3FF",
    "Public Relations": "#FFB7CE",
    "Vegetarian": "#A0D8EF",
    "Parks & Campgrounds": "#B2A4E4",
    "Guitar": "#A8E6CF",
    "Physical Therapy": "#FFDDC1",
    "Judicial Power": "#FF9AA2",
    "19th Century": "#C2B2DA",
    "Oncology & Cancer": "#FFD1DC",
    "Electronic Publishing": "#FFCCB6",
    "Exports & Imports": "#C1A3FF",
    "Trivia": "#FFB7CE",
    "Romance": "#A0D8EF",
    "Applied Sciences": "#B2A4E4",
    "Presidents & First Families (U.S.)": "#A8E6CF",
    "Holiday": "#FFDDC1",
    "Walking": "#FF9AA2",
    "Restaurants": "#C2B2DA",
    "Eating Disorders": "#FFD1DC",
    "Money Management": "#FFCCB6",
    "Administrative Law & Regulatory Practice": "#C1A3FF",
    "Aims & Objectives": "#FFB7CE",
    "Adolescence & Coming of Age": "#A0D8EF",
    "Geography": "#B2A4E4",
    "Science & Nature": "#A8E6CF",
    "MN": "#FFDDC1",
    "Australia & New Zealand": "#FF9AA2",
    "ACT": "#C2B2DA",
    "Garnishing & Food Presentation": "#FFD1DC",
    "Couples & Family": "#FFCCB6",
    "Interior Design": "#C1A3FF",
    "College Guides": "#FFB7CE",
    "Petroleum": "#A0D8EF",
    "Bottles": "#B2A4E4",
    "Early Childhood (incl. Preschool & Kindergarten)": "#A8E6CF",
    "Shrubs": "#FFDDC1",
    "Time": "#FF9AA2",
    "Purchasing & Buying": "#C2B2DA",
    "Birdwatching Guides": "#FFD1DC",
    "Sky Observation": "#FFCCB6",
    "Discipleship": "#C1A3FF",
    "Quantum Theory": "#FFB7CE",
    "Bereavement": "#A0D8EF",
    "Drafting": "#B2A4E4",
    "Fossils": "#A8E6CF",
    "Chemistry": "#FFDDC1",
    "Counting & Numbers": "#FF9AA2",
    "Landscape": "#C2B2DA",
    "Beauty & Grooming": "#FFD1DC",
    "Neuroscience": "#FFCCB6",
    "Etymology": "#C1A3FF",
    "Caribbean & Latin America": "#FFB7CE",
    "Matrices": "#A0D8EF",
    "Cell Biology": "#B2A4E4",
    "Elections": "#A8E6CF",
    "Biotechnology": "#FFDDC1",
    "Web": "#FF9AA2",
    "School Safety": "#C2B2DA",
    "Mental Health": "#FFD1DC",
    "Social Policy": "#FFCCB6",
    "Southeast Asia": "#C1A3FF",
    "IN": "#FFB7CE",
    "South America": "#A0D8EF",
    "Students & Student Life": "#B2A4E4",
    "Rhetoric": "#A8E6CF",
    "Baby Names": "#FFDDC1",
    "Security": "#FF9AA2",
    "Diabetes": "#C2B2DA",
    "Natural Disasters": "#FFD1DC",
    "Mennonite": "#FFCCB6",
    "Online Safety & Privacy": "#C1A3FF",
    "Self-Management": "#FFB7CE",
    "Ophthalmology": "#A0D8EF",
    "Systems Analysis & Design": "#B2A4E4",
    "Yiddish": "#A8E6CF",
    "Theory & Social Aspects": "#FFDDC1",
    "Architecture": "#C2B2DA",
    "Psychology": "#FFD1DC",
    "Breastfeeding": "#FFCCB6",
    "Motorcycles": "#C1A3FF",
    "Portraits": "#FFB7CE",
    "Water Sports": "#A0D8EF",
    "Racquetball": "#B2A4E4",
    "Home & Community Care": "#A8E6CF",
    "Dictionaries & Encyclopedias": "#FFDDC1",
    "Theology": "#FF9AA2",
    "Business & Professional": "#C2B2DA",
    "Ancient & Classical": "#FFD1DC",
    "Occult & Supernatural": "#FFCCB6",
    "Agnosticism": "#C1A3FF",
    "Aging": "#FFB7CE",
    "Motivational & Inspirational": "#A0D8EF",
    "Authorship": "#B2A4E4",
    "Courts": "#A8E6CF",
    "Sexual Abuse": "#FFDDC1",
    "Fantasy & Magic": "#FF9AA2",
    "Decorative Arts": "#C2B2DA",
    "Counseling": "#FFD1DC",
    "Multilevel": "#FFCCB6",
    "Taoism": "#C1A3FF",
    "Swimming & Diving": "#FFB7CE",
    "Abortion & Birth Control": "#A0D8EF",
    "Men's Health": "#B2A4E4",
    "Tobacco-Related": "#A8E6CF",
    "Literary": "#FFDDC1",
    "Economic History": "#FF9AA2",
    "Women's Studies": "#C2B2DA",
    "Environmental Conservation & Protection": "#FFD1DC",
    "Triathlon": "#FFCCB6",
    "Oceans & Seas": "#C1A3FF",
    "Health & Fitness": "#FFB7CE",
    "Electronics": "#A0D8EF",
    "Oceania": "#B2A4E4",
    "Far East": "#A8E6CF",
    "Object Oriented": "#FFDDC1",
    "Translating & Interpreting": "#FF9AA2",
    "Advertising": "#C2B2DA",
    "Zen": "#FFD1DC",
    "Genealogy & Heraldry": "#FFCCB6",
    "Seasons": "#C1A3FF",
    "Crime": "#FFB7CE",
    "Legal Writing": "#A0D8EF",
    "Chemotherapy": "#B2A4E4",
    "Education & Training": "#A8E6CF",
    "Diet & Nutrition": "#FFDDC1",
    "Addiction": "#FF9AA2",
    "Alien Contact": "#C2B2DA",
    "France": "#FFD1DC",
    "Epidemiology": "#FFCCB6",
    "Continental European": "#C1A3FF",
    "Art & Architecture": "#FFB7CE",
    "Jewish Studies": "#A0D8EF",
    "Perinatology & Neonatology": "#B2A4E4",
    "Microeconomics": "#A8E6CF",
    "Weight Loss": "#FFDDC1",
    "UNIX": "#FF9AA2",
    "GMAT (Graduate Management Admission Test)": "#C2B2DA",
    "Legal": "#FFD1DC",
    "Dysfunctional Families": "#FFCCB6",
    "Native American Studies": "#C1A3FF",
    "Asia": "#FFB7CE",
    "Apes": "#A0D8EF",
    "Travel": "#B2A4E4",
    "Jokes & Riddles": "#A8E6CF",
    "Applied": "#FFDDC1",
    "Design & Construction": "#FF9AA2",
    "Skin": "#C2B2DA",
    "PE)": "#FFD1DC",
    "Great Britain": "#FFCCB6",
    "Research": "#C1A3FF",
    "Campaigns & Elections": "#FFB7CE",
    "Leopards": "#A0D8EF",
    "Cacti & Succulents": "#B2A4E4",
    "21st Century": "#A8E6CF",
    "Survival": "#FFDDC1",
    "Public Policy": "#FF9AA2",
    "City Planning & Urban Development": "#C2B2DA",
    "New England (CT": "#FFD1DC",
    "Jazz": "#FFCCB6",
    "Drawing": "#C1A3FF",
    "Literary Collections": "#FFB7CE",
    "Finance": "#A0D8EF",
    "Nature": "#B2A4E4",
    "New Business Enterprises": "#A8E6CF",
    "Austria & Hungary": "#FFDDC1",
    "NH": "#FF9AA2",
    "Stuffed Animals": "#C2B2DA",
    "Musical Instruments": "#FFD1DC",
    "Friendship": "#FFCCB6",
    "House Plants & Indoor": "#C1A3FF",
    "Horses": "#FFB7CE",
    "New Thought": "#A0D8EF",
    "Australian & Oceanian": "#B2A4E4",
    "Oil Painting": "#A8E6CF",
    "Care & Restoration": "#FFDDC1",
    "Old Testament": "#FF9AA2",
    "Intelligence & Espionage": "#C2B2DA",
    "Hikes & Walks": "#FFD1DC",
    "Photoessays & Documentaries": "#FFCCB6",
    "Relativity": "#C1A3FF",
    "Discography & Buyer's Guides": "#FFB7CE",
    "Investing": "#A0D8EF",
    "Behaviorism": "#B2A4E4",
    "Epistemology": "#A8E6CF",
    "Israel & Palestine": "#FFDDC1",
    "Personal Success": "#FF9AA2",
    "Repair": "#C2B2DA",
    "Propaganda": "#FFD1DC",
    "Pies": "#FFCCB6",
    "Concordances": "#C1A3FF",
    "Directories": "#FFB7CE",
    "Hispanic & Latino": "#A0D8EF",
    "Spices": "#B2A4E4",
    "Information Theory": "#A8E6CF",
    "Cultural Policy": "#FFDDC1",
    "Growth": "#FF9AA2",
    "Holiday & Seasonal": "#C2B2DA",
    "Screenplays": "#FFD1DC",
    "LGBT Studies": "#FFCCB6",
    "Trees & Forests": "#C1A3FF",
    "Business Aspects": "#FFB7CE",
    "Men": "#A0D8EF",
    "Historical": "#B2A4E4",
    "Sustainability & Green Design": "#A8E6CF",
    "Arthurian": "#FFDDC1",
    "Psychology of Religion": "#FF9AA2",
    "Trees": "#C2B2DA",
    "Italy": "#FFD1DC",
    "Foreign Exchange": "#FFCCB6",
    "Pain Management": "#C1A3FF",
    "KY": "#FFB7CE",
    "Thanksgiving": "#A0D8EF",
    "Diagnostic Imaging": "#B2A4E4",
    "Porcelain & China": "#A8E6CF",
    "Peer Pressure": "#FFDDC1",
    "Perinatal": "#FF9AA2",
    "Nonprofit Organizations & Charities": "#C2B2DA",
    "Teaching Methods & Materials": "#FFD1DC",
    "NC": "#FFCCB6",
    "Boating": "#C1A3FF",
    "Composers & Musicians": "#FFB7CE",
    "International Mystery & Crime": "#A0D8EF",
    "Atlases & Gazetteers": "#B2A4E4",
    "Evangelism": "#A8E6CF",
    "Conflict Resolution": "#FF9AA2",
    "Fables": "#C2B2DA",
    "User Interfaces": "#FFD1DC",
    "Emotional & Social Disabilities": "#FFCCB6",
    "Organizational Development": "#C1A3FF",
    "Vocabulary": "#FFB7CE",
    "Occupations": "#A0D8EF",
    "Farm & Ranch Life": "#B2A4E4",
    "African American Studies": "#A8E6CF",
    "Size & Shape": "#FFDDC1",
    "Painting": "#FF9AA2",
    "Buyer's Guides": "#C2B2DA",
    "Medieval": "#FFD1DC",
    "Vietnamese": "#FFCCB6",
    "Student Life & Student Affairs": "#C1A3FF",
    "Cardiology": "#FFB7CE",
    "Appreciation": "#A0D8EF",
    "Parodies": "#B2A4E4",
    "Emigration & Immigration": "#A8E6CF",
    "Revolutionary Period (1775-1800)": "#FFDDC1",
    "Histology": "#FF9AA2",
    "Topology": "#C2B2DA",
    "WY)": "#FFD1DC",
    "Embryology": "#FFCCB6",
    "LGBT": "#C1A3FF",
    "Lions": "#FFB7CE",
    "Political Ideologies": "#A0D8EF",
    "Defamation": "#B2A4E4",
    "Elementary": "#A8E6CF",
    "Rocks & Minerals": "#FFDDC1",
    "Mathematical & Statistical Software": "#FF9AA2",
    "Macintosh": "#C2B2DA",
    "Essays & Narratives": "#FFD1DC",
    "English as a Second Language": "#FFCCB6",
    "Caretaking & Organizing": "#C1A3FF",
    "Cookies": "#FFB7CE",
    "Power Tools": "#A0D8EF",
    "Energy": "#B2A4E4",
    "Business Etiquette": "#A8E6CF",
    "Auditing": "#FFDDC1",
    "Demography": "#FF9AA2",
    "International": "#C2B2DA",
    "Do-It-Yourself": "#FFD1DC",
    "Traditions": "#FFCCB6",
    "Self-Esteem": "#C1A3FF",
    "MI": "#FFB7CE",
    "Mountaineering": "#A0D8EF",
    "Anatomy & Physiology": "#B2A4E4",
    "Botany": "#A8E6CF",
    "Sports Psychology": "#FFDDC1",
    "Monasticism": "#FF9AA2",
    "Nutrition": "#C2B2DA",
    "Photojournalism": "#FFD1DC",
    "Comparative": "#FFCCB6",
    "Gynecology & Obstetrics": "#C1A3FF",
    "Marriage": "#FFB7CE",
    "Curiosities & Wonders": "#A0D8EF",
    "Butterflies & Moths": "#B2A4E4",
    "Sikhism": "#A8E6CF",
    "Mathematical & Computational": "#FFDDC1",
    "Visionary & Metaphysical": "#FF9AA2",
    "English Standard Version": "#C2B2DA",
    "Navigation": "#FFD1DC",
    "Lodging & Transportation": "#FFCCB6",
    "Senior": "#C1A3FF",
    "Korea": "#FFB7CE",
    "Desktop Applications": "#A0D8EF",
    "Lesbian Studies": "#B2A4E4",
    "Plants & Animals": "#A8E6CF",
    "White Collar Crime": "#FFDDC1",
    "Decorating & Furnishings": "#FF9AA2",
    "Ethnomusicology": "#C2B2DA",
    "Schizophrenia": "#FFD1DC",
    "Graduate School Guides": "#FFCCB6",
    "India": "#C1A3FF",
    "Civil": "#FFB7CE",
    "Women Artists": "#A0D8EF",
    "Judaism": "#B2A4E4",
    "Motor Sports": "#A8E6CF",
    "Politics": "#FFDDC1",
    "Orphans & Foster Homes": "#FF9AA2",
    "Systems Architecture": "#C2B2DA",
    "Discrete Mathematics": "#FFD1DC",
    "Nervous System (incl. Brain)": "#FFCCB6",
    "Cajun & Creole": "#C1A3FF",
    "XML": "#FFB7CE",
    "Garden Furnishings": "#A0D8EF",
    "Spiritual": "#B2A4E4",
    "Quality Control": "#A8E6CF",
    "Preventive Medicine": "#FFDDC1",
    "Cleaning": "#FF9AA2",
    "Spanish & Portuguese": "#C2B2DA",
    "Satire": "#FFD1DC",
    "Writing": "#FFCCB6",
    "Songwriting": "#C1A3FF",
    "Revolutionary": "#FFB7CE",
    "Retailing": "#A0D8EF",
    "Telepathy)": "#B2A4E4",
    "Criticism": "#A8E6CF",
    "Atomic & Molecular": "#FFDDC1",
    "Diagnosis": "#FF9AA2",
    "Toymaking": "#C2B2DA",
    "Literary Criticism": "#FFD1DC",
    "Microbiology": "#FFCCB6",
    "Labor & Employment": "#C1A3FF",
    "Asian American": "#FFB7CE",
    "Contemporary English Version": "#A0D8EF",
    "Masonry": "#B2A4E4",
    "Parents": "#A8E6CF",
    "Framing": "#FFDDC1",
    "Frogs & Toads": "#FF9AA2",
    "Sociology": "#C2B2DA",
    "Safety": "#FFD1DC",
    "Lacrosse": "#FFCCB6",
    "Poverty & Homelessness": "#C1A3FF",
    "Methodology": "#FFB7CE",
    "Macroeconomics": "#A0D8EF",
    "First Aid": "#B2A4E4",
    "West (AK": "#A8E6CF",
    "Local": "#FFDDC1",
    "Strategy": "#FF9AA2",
    "Boys & Men": "#C2B2DA",
    "Family Life": "#FFD1DC",
    "MT": "#FFCCB6",
    "Darkroom": "#C1A3FF",
    "Public Finance": "#FFB7CE",
    "Writing Skills": "#A0D8EF",
    "Medical (incl. Patients)": "#B2A4E4",
    "Personal Hygiene": "#A8E6CF",
    "ESP (Clairvoyance": "#FFDDC1",
    "Philosophers": "#FF9AA2",
    "Classical & Medieval": "#C2B2DA",
    "Railroads": "#FFD1DC",
    "Embroidery": "#FFCCB6",
    "Literary Criticism & Collections": "#C1A3FF",
    "Publishing": "#FFB7CE",
    "Basketball": "#A0D8EF",
    "Calligraphy": "#B2A4E4",
    "Caribbean & West Indies": "#A8E6CF",
    "Psychiatry": "#FFDDC1",
    "Crafts for Children": "#FF9AA2",
    "Woodwork": "#C2B2DA",
    "Study Guides": "#FFD1DC",
    "Drugs": "#FFCCB6",
    "Spanish": "#C1A3FF",
    "Human Rights": "#FFB7CE",
    "Board Games": "#A0D8EF",
    "Literature & the Arts": "#B2A4E4",
    "Computer Engineering": "#A8E6CF",
    "Apple (Mac OS & iOS)": "#FFDDC1",
    "Personal Finance": "#FF9AA2",
    "Cognitive Neuroscience & Cognitive Neuropsychology": "#C2B2DA",
    "OK": "#FFD1DC",
    "Traditional": "#FFCCB6",
    "MA": "#C1A3FF",
    "Leadership": "#FFB7CE",
    "Mind & Spirit": "#A0D8EF",
    "Time Travel": "#B2A4E4",
    "Australia & Oceania": "#A8E6CF",
    "New England": "#FFDDC1",
    "Mountain (AZ": "#FF9AA2",
    "Eating Disorders & Body Image": "#C2B2DA",
    "Anger Management": "#FFD1DC",
    "Spain & Portugal": "#FFCCB6",
    "LA": "#C1A3FF",
    "Atlases": "#FFB7CE",
    "Women Authors": "#A0D8EF",
    "Special Forces": "#B2A4E4",
    "Inns & Hostels": "#A8E6CF",
    "Consumer Behavior": "#FFDDC1",
    "Entertainment & Games": "#FF9AA2",
    "Property": "#C2B2DA",
    "Knitting": "#FFD1DC",
    "Business": "#FFCCB6",
    "Collections & Anthologies": "#C1A3FF",
    "India & South Asia": "#FFB7CE",
    "Advertising & Promotion": "#A0D8EF",
    "Management Information Systems": "#B2A4E4",
    "Study & Test-Taking Skills": "#A8E6CF",
    "Strategic Planning": "#FFDDC1",
    "Good & Evil": "#FF9AA2",
    "Firearms & Weapons": "#C2B2DA",
    "Slow Cooking": "#FFD1DC",
    "Governmental": "#FFCCB6",
    "Legal History": "#C1A3FF",
    "Reform": "#FFB7CE",
    "Single Parent": "#A0D8EF",
    "Programming": "#B2A4E4",
    "Furniture": "#A8E6CF",
    "Estates & Trusts": "#FFDDC1",
    "Ethnic Studies": "#FF9AA2",
    "Environmental": "#C2B2DA",
    "Adventure & Adventurers": "#FFD1DC",
    "Baking": "#FFCCB6",
    "Central & South America": "#C1A3FF",
    "Money & Monetary Policy": "#FFB7CE",
    "Instruction & Study": "#A0D8EF",
    "Juvenile Nonfiction": "#B2A4E4",
    "Learning Disabilities": "#A8E6CF",
    "Printed Music": "#FFDDC1",
    "Decoration & Ornament": "#FF9AA2",
    "Network Protocols": "#C2B2DA",
    "Text": "#FFD1DC",
    "VA": "#FFCCB6",
    "East": "#C1A3FF",
    "Aerobics": "#FFB7CE",
    "Rome": "#A0D8EF",
    "People with Disabilities": "#B2A4E4",
    "Constitutions": "#A8E6CF",
    "Collaboration Software": "#FFDDC1",
    "Classic & Allegory": "#FF9AA2",
    "Veterans": "#C2B2DA",
    "Educational Law & Legislation": "#FFD1DC",
    "Logic & Brain Teasers": "#C1A3FF",
    "Twelve-Step Programs": "#FFB7CE",
    "Curricula": "#A0D8EF",
    "Social Topics": "#B2A4E4",
    "Home-Based Businesses": "#A8E6CF",
    "Immunology": "#FFDDC1",
    "Homeopathy": "#FF9AA2",
    "Presbyterian": "#C2B2DA",
    "Media & the Law": "#FFD1DC",
    "Leadership & Mentoring": "#FFCCB6",
    "Interactive Adventures": "#C1A3FF",
    "Graphic Arts": "#FFB7CE",
    "Apologetics": "#A0D8EF",
    "Legends & Mythology": "#B2A4E4",
    "Discrimination & Race Relations": "#A8E6CF",
    "Diet Therapy": "#FFDDC1",
    "Decorating": "#FF9AA2",
    "DE": "#C2B2DA",
    "Molecular Biology": "#FFD1DC",
    "Seasonal": "#FFCCB6",
    "Wildflowers": "#C1A3FF",
    "Composition": "#FFB7CE",
    "Politics & Government": "#A0D8EF",
    "Bulbs": "#B2A4E4",
    "Sailing": "#A8E6CF",
    "Stepparenting": "#FFDDC1",
    "Shade": "#FF9AA2",
    "Concepts": "#C2B2DA",
    "Nonfiction (incl. Memoirs)": "#FFD1DC",
    "FL": "#FFCCB6",
    "Criminal Law": "#C1A3FF",
    "Cross-Stitch": "#FFB7CE",
    "Inclusive Education": "#A0D8EF",
    "Drama": "#B2A4E4",
    "Astrology": "#A8E6CF",
    "Visual BASIC": "#FFDDC1",
    "Fire Science": "#FF9AA2",
    "Guides & Reviews": "#C2B2DA",
    "Emotions & Feelings": "#FFD1DC",
    "Psychotherapy": "#C1A3FF",
    "Supernatural (incl. Ghosts)": "#FFB7CE",
    "Remodeling & Renovation": "#A0D8EF",
    "Colonial & Revolutionary Periods": "#B2A4E4",
    "Christian Theology": "#A8E6CF",
    "Mind & Body": "#FFDDC1",
    "Teddy Bears": "#FF9AA2",
    "Criticism & Theory": "#C2B2DA",
    "Parapsychology": "#FFD1DC",
    "Gourmet": "#FFCCB6",
    "Rock": "#C1A3FF",
    "Non-Religious": "#FFB7CE",
    "Mediterranean": "#A0D8EF",
    "Pop Vocal": "#B2A4E4",
    "Inspirational & Religious": "#A8E6CF",
    "West North Central (IA": "#FFDDC1",
    "Diplomacy": "#FF9AA2",
    "Psychiatric": "#C2B2DA",
    "Corporate & Business History": "#FFD1DC",
    "Korean": "#FFCCB6",
    "Nursing": "#C1A3FF",
    "Construction": "#FFB7CE",
    "Social Activists": "#A0D8EF",
    "Sexual Instruction": "#B2A4E4",
    "A+": "#A8E6CF",
    "ME": "#FFDDC1",
    "Stress Management": "#FF9AA2",
    "Cryptography": "#C2B2DA",
    "Horoscopes": "#FFD1DC",
    "Political Process": "#FFCCB6",
    "Nonfiction": "#C1A3FF",
    "Greenhouses": "#FFB7CE",
    "Pirates": "#A0D8EF",
    "Video & Animation": "#B2A4E4",
    "Clocks & Watches": "#A8E6CF",
    "Agribusiness": "#FFDDC1",
    "Massage & Reflexotherapy": "#FF9AA2",
    "Parenting": "#C2B2DA",
    "Pacific (AK": "#FFD1DC",
    "Spelling & Vocabulary": "#FFCCB6",
    "Plumbing": "#C1A3FF",
    "Reiki": "#FFB7CE",
    "Essays & Travelogues": "#A0D8EF",
    "Acrylic Painting": "#B2A4E4",
    "Confucianism": "#A8E6CF",
    "Entertaining": "#FFDDC1",
    "Outdoor": "#FF9AA2",
    "Emotions": "#C2B2DA",
    "Denominations": "#FFD1DC",
    "Mathematics": "#FFCCB6",
    "Road Travel": "#C1A3FF",
    "Lasers in Medicine": "#FFB7CE",
    "Structural Adjustment": "#A0D8EF",
    "Weapons": "#B2A4E4",
    "Pulmonary & Thoracic Medicine": "#A8E6CF",
    "Pathophysiology": "#FFDDC1",
    "Adventure": "#FF9AA2",
    "South Atlantic (DC": "#C2B2DA",
    "Meditation": "#FFD1DC",
    "Testing & Measurement": "#FFCCB6",
    "Blackjack": "#C1A3FF",
    "Bullying": "#FFB7CE",
    "Orthopedics": "#A0D8EF",
    "Vegan": "#B2A4E4",
    "Survival Stories": "#A8E6CF",
    "Prophecy": "#FFDDC1",
    "Artists": "#FF9AA2",
    "Bankruptcy & Insolvency": "#C2B2DA",
    "Autographs": "#FFD1DC",
    "Opera": "#FFCCB6",
    "Condiments": "#C1A3FF",
    "Latin": "#FFB7CE",
    "Pigs": "#A0D8EF",
    "Other English Translations": "#B2A4E4",
    "Cancer": "#A8E6CF",
    "Sleep & Sleep Disorders": "#FFDDC1",
    "Missions": "#FF9AA2",
    "Research & Methodology": "#C2B2DA",
    "Baptist": "#FFD1DC",
    "Personal Growth": "#FFCCB6",
    "Urban Life": "#C1A3FF",
    "KS": "#FFB7CE",
    "Entertainment & Performing Arts": "#A0D8EF",
    "Christian Church": "#B2A4E4",
    "Monsters": "#A8E6CF",
    "Theater & Musicals": "#FFDDC1",
    "Manners & Etiquette": "#FF9AA2",
    "Ethnic & Tribal": "#C2B2DA",
    "Pneumatology": "#FFD1DC",
    "Windows Server & NT": "#FFCCB6",
    "Contemporary": "#C1A3FF",
    "Hymns": "#FFB7CE",
    "Legal Services": "#A0D8EF",
    "Teddy Bears & Stuffed Animals": "#B2A4E4",
    "Family & Relationships": "#A8E6CF",
    "Portraits & Selfies": "#FFDDC1",
    "Personal & Practical Guides": "#FF9AA2",
    "Literacy": "#C2B2DA",
    "Hard-Boiled": "#FFD1DC",
    "Romantic Comedy": "#FFCCB6",
    "System Administration": "#C1A3FF",
    "Luxembourg)": "#FFB7CE",
    "Prayer": "#A0D8EF",
    "Presidents & Heads of State": "#B2A4E4",
    "Modern": "#A8E6CF",
    "Self-help": "#FFDDC1",
    "System Theory": "#FF9AA2",
    "Caribbean & Latin American": "#C2B2DA",
    "Folk & Outsider Art": "#FFD1DC",
    "Pentecostal & Charismatic": "#FFCCB6",
    "Chaotic Behavior in Systems": "#C1A3FF",
    "Japan": "#FFB7CE",
    "Greece": "#A0D8EF",
    "Circuits": "#B2A4E4",
    "Television: National Geographic": "#A8E6CF",
    "Classics": "#FFDDC1",
    "Magical Realism": "#FF9AA2",
    "Pottery & Ceramics": "#C2B2DA",
    "Windows Desktop": "#FFD1DC",
    "Hispanic American Studies": "#FFCCB6",
    "Books & Libraries": "#C1A3FF",
    "Comparative Politics": "#FFB7CE",
    "Inspirational": "#A0D8EF",
    "Autism Spectrum Disorders": "#B2A4E4",
    "CA": "#A8E6CF",
    "Middle Western States": "#FFDDC1",
    "Portuguese": "#FF9AA2",
    "Desserts": "#C2B2DA",
    "Legal Profession": "#FFD1DC",
    "Agriculture & Food": "#FFCCB6",
    "NY": "#C1A3FF",
    "Wrestling": "#FFB7CE",
    "Welsh": "#A0D8EF",
    "Civil Rights": "#B2A4E4",
    "Almanacs": "#A8E6CF",
    "Collections": "#FFDDC1",
    "Fishes": "#FF9AA2",
    "Pain Medicine": "#C2B2DA",
    "Anatomy": "#FFD1DC",
    "Theater": "#FFCCB6",
    "Workplace Culture": "#C1A3FF",
    "Fish & Aquariums": "#FFB7CE",
    "Civil Procedure": "#A0D8EF",
    "Reading Skills": "#B2A4E4",
    "Pediatric & Neonatal": "#A8E6CF",
    "Study Aids": "#FFDDC1",
    "Model Railroading": "#FF9AA2",
    "Practical Guides": "#C2B2DA",
    "Spreadsheets": "#FFD1DC",
    "Fitness & Exercise": "#FFCCB6",
    "Poetry": "#C1A3FF",
    "Marriage & Long-Term Relationships": "#FFB7CE",
    "Ancient Mysteries & Controversial Knowledge": "#A0D8EF",
    "Scientology": "#B2A4E4",
    "Commercial & Industrial": "#A8E6CF",
    "Pragmatism": "#FFDDC1",
    "Colors": "#C2B2DA",
    "Culinary": "#FFD1DC",
    "Holidays (non-religious)": "#FFCCB6",
    "HI": "#C1A3FF",
    "How Things Work-Are Made": "#FFB7CE",
    "Scottish & Welsh": "#A0D8EF",
    "Individual Architects & Firms": "#B2A4E4",
    "Hotels": "#A8E6CF",
    "Dye": "#FFDDC1",
    "Imaging Technologies": "#FF9AA2",
    "Codependency": "#C2B2DA",
    "Fatherhood": "#FFD1DC",
    "Austria": "#FFCCB6",
    "Liberation": "#C1A3FF",
    "MS": "#FFB7CE",
    "Mammals": "#A0D8EF",
    "Children's & Young Adult Literature": "#B2A4E4",
    "Mexico": "#A8E6CF",
    "Biblical Reference": "#FFDDC1",
    "Health Care Issues": "#FF9AA2",
    "Censorship": "#C2B2DA",
    "Fairy Tales": "#FFD1DC",
    "Letters": "#FFCCB6",
    "Bridge": "#C1A3FF",
    "Camping & Outdoor Activities": "#FFB7CE",
    "Extended Family": "#A0D8EF",
    "Neuropsychology": "#B2A4E4",
    "Holism": "#A8E6CF",
    "Coyotes & Wild Dogs": "#FFDDC1",
    "Games & Activities": "#FF9AA2",
    "Native American & Aboriginal": "#C2B2DA",
    "Consumer Guides": "#FFD1DC",
    "Track & Field": "#FFCCB6",
    "Production & Operations Management": "#C1A3FF",
    "Classroom Management": "#FFB7CE",
    "Antitrust": "#A0D8EF",
    "Other": "#B2A4E4",
    "Business Ethics": "#A8E6CF",
    "Courses & Dishes": "#FFDDC1",
    "Protestant": "#FF9AA2",
    "Adult": "#C2B2DA",
    "Health & Daily Living": "#FFD1DC",
    "SAT": "#FFCCB6",
    "Software Development & Engineering": "#C1A3FF",
    "Role Playing & Fantasy": "#FFB7CE",
    "Legislative Branch": "#A0D8EF",
    "Landscapes": "#B2A4E4",
    "etc.": "#A8E6CF",
    "Education": "#FFDDC1",
    "Naturopathy": "#FF9AA2",
    "MO": "#C2B2DA",
    "Equestrian": "#FFD1DC",
    "School & Education": "#FFCCB6",
    "Lasers & Photonics": "#C1A3FF",
    "Mobile Devices": "#FFB7CE",
    "Westerns": "#A0D8EF",
    "Retirement Planning": "#B2A4E4",
    "Spiritual Growth": "#A8E6CF",
    "Air Sports": "#FFDDC1",
    "Internal Medicine": "#FF9AA2",
    "Roses": "#C2B2DA",
    "Amish": "#FFD1DC",
    "Philosophy": "#FFCCB6",
    "Methods": "#C1A3FF",
    "Books": "#FFB7CE",
    "Paleontology": "#A0D8EF",
    "Personal Finance Applications": "#B2A4E4",
    "Ballet": "#A8E6CF",
    "Infinity": "#FFDDC1",
    "Naval": "#FF9AA2",
    "Anthropology": "#C2B2DA",
    "Origami": "#FFD1DC",
    "Child & Adolescent": "#FFCCB6",
    "Physical": "#C1A3FF",
    "Folkcrafts": "#FFB7CE",
    "Passover": "#A0D8EF",
    "Media & Communications": "#B2A4E4",
    "Applied Psychology": "#A8E6CF",
    "NJ": "#FFDDC1",
    "Roller & In-Line Skating": "#FF9AA2",
    "Prehistory": "#C2B2DA",
    "Rich & Famous": "#FFD1DC",
    "Optical Illusions": "#FFCCB6",
    "Taxonomy": "#C1A3FF",
    "Dolls": "#FFB7CE",
    "Repair & Maintenance": "#A0D8EF",
    "Ghost": "#B2A4E4",
    "Regional Studies": "#A8E6CF",
    "Specific Ingredients": "#FFDDC1",
    "Practice Management & Reimbursement": "#FF9AA2",
    "GRE (Graduate Record Examination)": "#C2B2DA",
    "Statistics": "#FFD1DC",
    "Regional & Ethnic": "#FFCCB6",
    "Browsers": "#C1A3FF",
    "Law": "#FFB7CE",
    "New Baby": "#A0D8EF",
    "Rabbits": "#B2A4E4",
    "Aeronautics & Astronautics": "#A8E6CF",
    "Document Management": "#FFDDC1",
    "WI)": "#FF9AA2",
    "Switzerland": "#C2B2DA",
    "Opposites": "#FFD1DC",
    "Indian & South Asian": "#FFCCB6",
    "Nursery Rhymes": "#C1A3FF",
    "Catholic": "#FFB7CE",
    "Architectural & Industrial": "#A0D8EF",
    "Reproductive Medicine & Technology": "#B2A4E4",
    "Environmental Economics": "#A8E6CF",
    "Reading & Phonics": "#FFDDC1",
    "Acupressure & Acupuncture": "#FF9AA2",
    "Political Freedom & Security": "#C2B2DA",
    "Adulthood & Aging": "#FFD1DC",
    "Word Processing": "#FFCCB6",
    "Railroads & Trains": "#C1A3FF",
    "Spiritual Warfare": "#FFB7CE",
    "Chocolate": "#A0D8EF",
    "Multicultural Education": "#B2A4E4",
    "Infants & Toddlers": "#A8E6CF",
    "Virtual Worlds": "#FFDDC1",
    "Divorce & Separation": "#FF9AA2",
    "Football": "#C2B2DA",
    "Hospital Administration & Care": "#FFD1DC",
    "Manufacturing": "#FFCCB6",
    "Certification Guides": "#C1A3FF",
    "Weather": "#FFB7CE",
    "Men's Interests": "#A0D8EF",
    "Poker": "#B2A4E4",
    "Occultism": "#A8E6CF",
    "Individual Composer & Musician": "#FFDDC1",
    "Counting & Numeration": "#FF9AA2",
    "Nanotechnology & MEMS": "#C2B2DA",
    "Devotional": "#FFD1DC",
    "Diabetic & Sugar-Free": "#FFCCB6",
    "Police Procedural": "#C1A3FF",
    "Sweden)": "#FFB7CE",
    "Cleaning & Caretaking": "#A0D8EF",
    "Encyclopedias": "#B2A4E4",
    "House Plans": "#A8E6CF",
    "Valentine's Day": "#FFDDC1",
    "Fish": "#FF9AA2",
    "Appetizers": "#C2B2DA",
    "Card Games": "#FFD1DC",
    "German": "#FFCCB6",
    "Political Parties": "#C1A3FF",
    "Gay": "#FFB7CE",
    "Tennis": "#A0D8EF",
    "Jewish": "#B2A4E4",
    "Time Management": "#A8E6CF",
    "Educational Psychology": "#FFDDC1",
    "Psychopathology": "#FF9AA2",
    "Terminal Care": "#C2B2DA",
    "Commercial & Corporate": "#FFD1DC",
    "Political": "#FFCCB6",
    "Executive Branch": "#C1A3FF",
    "American Government": "#FFB7CE",
    "Presentation Software": "#A0D8EF",
    "Adolescence": "#B2A4E4",
    "Child": "#A8E6CF",
    "Scandinavian Languages (Other)": "#FFDDC1",
    "Veterinary Medicine": "#FF9AA2",
    "NE": "#C2B2DA",
    "Suspense": "#FFD1DC",
    "Voice": "#FFCCB6",
    "AIDS & HIV": "#C1A3FF",
    "Western States": "#FFB7CE",
    "Folklore & Mythology": "#A0D8EF",
    "Orthodox": "#B2A4E4",
    "Later Years": "#A8E6CF",
    "Table": "#FFDDC1",
    "Polarity)": "#FF9AA2",
    "Watercolor Painting": "#C2B2DA",
    "Heart": "#FFD1DC",
    "Developmental": "#FFCCB6",
    "Urban": "#C1A3FF",
    "Engineering (General)": "#FFB7CE",
    "Young Adult Nonfiction": "#A0D8EF",
    "Aesthetics": "#B2A4E4",
    "Mysteries & Detective Stories": "#A8E6CF",
    "Form": "#FFDDC1",
    "Security (National & International)": "#FF9AA2",
    "Economic Conditions": "#C2B2DA",
    "Grammar & Punctuation": "#FFD1DC",
    "Pregnancy & Childbirth": "#FFCCB6",
    "Service": "#C1A3FF",
    "Garnishing": "#FFB7CE",
    "Bible Stories": "#A0D8EF",
    "Yearbooks & Annuals": "#B2A4E4",
    "Color Theory": "#A8E6CF",
    "Pencil Drawing": "#FFDDC1",
    "TX)": "#FF9AA2",
    "Residential": "#C2B2DA",
    "Stagecraft & Scenography": "#FFD1DC",
    "Insects & Spiders": "#FFCCB6",
    "Marketing": "#C1A3FF",
    "Aromatherapy": "#FFB7CE",
    "Low Cholesterol": "#A0D8EF",
    "Korean War": "#B2A4E4",
    "Computer & Internet": "#A8E6CF",
    "Love & Marriage": "#FFDDC1",
    "Skiing": "#FF9AA2",
    "Southwest (AZ": "#C2B2DA",
    "Insurance": "#FFD1DC",
    "Needlework": "#FFCCB6",
    "Networking": "#C1A3FF",
    "CO": "#FFB7CE",
    "Multi-Language Phrasebooks": "#A0D8EF",
    "Gold & Other Metals": "#B2A4E4",
    "Communication & Social Skills": "#A8E6CF",
    "Publishers & Publishing Industry": "#FFDDC1",
    "Cooking": "#FF9AA2",
    "Grandparenting": "#C2B2DA",
    "Assessment": "#FFD1DC",
    "Short Stories": "#FFCCB6",
    "War & Military": "#C1A3FF",
    "Date & Time": "#FFB7CE",
    "Entrepreneurship": "#A0D8EF",
    "Shaker": "#B2A4E4",
    "Anger": "#A8E6CF",
    "NGOs (Non-Governmental Organizations)": "#FFDDC1",
    "Disabilities & Special Needs": "#FF9AA2",
    "RI": "#C2B2DA",
    "Barbecue & Grilling": "#FFD1DC",
    "Stenciling": "#FFCCB6",
    "Episcopalian": "#C1A3FF",
    "Stories in Verse": "#FFB7CE",
    "Art & Politics": "#A0D8EF",
    "Peace": "#B2A4E4",
    "Rituals & Practice": "#A8E6CF",
    "Organic": "#FFDDC1",
    "Russia": "#FF9AA2",
    "Regional": "#C2B2DA",
    "Prayerbooks": "#FFD1DC",
    "Pregnancy": "#FFCCB6",
    "Landmarks & Monuments": "#C1A3FF",
    "Grammar": "#FFB7CE",
    "Massage & Reflexology": "#A0D8EF",
    "Computers": "#B2A4E4",
    "Black Humor": "#A8E6CF",
    "Vitamins": "#FFDDC1",
    "Caregiving": "#FF9AA2",
    "State & Provincial": "#C2B2DA",
    "Television": "#FFD1DC",
    "Christian Rituals & Practice": "#FFCCB6",
    "Alcohol": "#C1A3FF",
    "Circus": "#FFB7CE",
    "Drafting & Mechanical Drawing": "#A0D8EF",
    "Sauces & Dressings": "#B2A4E4",
    "Law Enforcement": "#A8E6CF",
    "Southern": "#FFDDC1",
    "Industrial & Organizational Psychology": "#FF9AA2",
    "Horse Racing": "#C2B2DA",
    "Managerial": "#FFD1DC",
    "Reptiles & Amphibians": "#FFCCB6",
    "Ceramics": "#C1A3FF",
    "Philosophy & Social Aspects": "#FFB7CE",
    "Cultural": "#A0D8EF",
    "Computers & Digital Media": "#B2A4E4",
    "Peripherals": "#A8E6CF",
    "Elephants": "#FFDDC1",
    "Christian Living": "#FF9AA2",
    "Pharmacy": "#C2B2DA",
    "Papercrafts": "#FFD1DC",
    "Adventurers & Explorers": "#FFCCB6",
    "Halloween": "#C1A3FF",
    "Mashups": "#FFB7CE",
    "Zoos": "#A0D8EF",
    "Bilingual Education": "#B2A4E4",
    "Toxicology": "#A8E6CF",
    "Intermediate": "#FFDDC1",
    "Physical & Emotional Abuse": "#FF9AA2",
    "Desktop Publishing": "#C2B2DA",
    "Nurse & Patient": "#FFD1DC",
    "Quantity": "#FFCCB6",
    "Lifespan Development": "#C1A3FF",
    "Confectionery": "#FFB7CE",
    "Facility Management": "#A0D8EF",
    "Clergy": "#B2A4E4",
    "History & Philosophy": "#A8E6CF",
    "Marriage & Family": "#FFDDC1",
    "Scuba & Snorkeling": "#FF9AA2",
    "Sustainable Development": "#C2B2DA",
    "Horror & Ghost Stories": "#FFD1DC",
    "Minority Studies": "#FFCCB6",
    "Girls & Women": "#C1A3FF",
    "Motherhood": "#FFB7CE",
    "Equipment": "#A0D8EF",
    "Reference": "#B2A4E4",
    "Activities": "#A8E6CF",
    "Political Freedom": "#FFDDC1",
    "Sexuality": "#FF9AA2",
    "Rugby": "#C2B2DA",
    "Social": "#FFD1DC",
    "Furniture & Cabinetry": "#FFCCB6",
    "Gymnastics": "#C1A3FF",
    "Cosmology": "#FFB7CE",
    "Ethics & Professional Responsibility": "#A0D8EF",
    "Applique": "#B2A4E4",
    "Baseball": "#A8E6CF",
    "Norway": "#FFDDC1",
    "Water (Oceans": "#FF9AA2",
    "Baseball & Softball": "#C2B2DA",
    "Evolution": "#FFD1DC",
    "Points of Interest": "#FFCCB6",
    "Pastry": "#C1A3FF",
    "Gerontology": "#FFB7CE",
    "Pictorial": "#A0D8EF",
    "Java": "#B2A4E4",
    "History & Surveys": "#A8E6CF",
    "Carving": "#FFDDC1",
    "Broadway & Musicals": "#FF9AA2",
    "Comic Strips & Cartoons": "#C2B2DA",
    "Cinematography & Videography": "#FFD1DC",
    "Database Management": "#FFCCB6",
    "New Revised Standard Version": "#C1A3FF",
    "Inspiration & Personal Growth": "#FFB7CE",
    "Foxes": "#A0D8EF",
    "Children & Youth": "#B2A4E4",
    "Sewing": "#A8E6CF",
    "Test Preparation": "#FFDDC1",
    "Physicians": "#FF9AA2",
    "Commercial Policy": "#C2B2DA",
    "Day Care & Child Care": "#FFD1DC",
    "Christian Life": "#FFCCB6",
    "Comparative Religion": "#C1A3FF",
    "Alternative History": "#FFB7CE",
    "Civilization": "#A0D8EF",
    "Logic": "#B2A4E4",
    "Biography & Autobiography": "#A8E6CF",
    "Values & Virtues": "#FFDDC1",
    "Emergency Medicine": "#FF9AA2",
    "World War I": "#C2B2DA",
    "Site Design": "#FFD1DC",
    "Globalization": "#FFCCB6",
    "OR": "#C1A3FF",
    "Eldercare": "#FFB7CE",
    "Public Speaking & Speech Writing": "#A0D8EF",
    "Ornithology": "#B2A4E4",
    "Olympics & Paralympics": "#A8E6CF",
    "Human-Computer Interaction (HCI)": "#FFDDC1",
    "Journaling": "#FF9AA2",
    "Architects": "#C2B2DA",
    "Americas (North": "#FFD1DC",
    "Herbs": "#FFCCB6",
    "Banks & Banking": "#C1A3FF",
    "Kwanzaa": "#FFB7CE",
    "Tours": "#A0D8EF",
    "Books & Reading": "#B2A4E4",
    "Children": "#A8E6CF",
    "Netherlands": "#FFDDC1",
    "North America": "#FF9AA2",
    "Oceanography": "#C2B2DA",
    "Babysitting": "#FFD1DC",
    "Shamanism": "#FFCCB6",
    "West": "#C1A3FF",
    "Arabic": "#FFB7CE",
    "Children's Music": "#A0D8EF",
    "Home Schooling": "#B2A4E4",
    "Social Security": "#A8E6CF",
    "Total Quality Management": "#FFDDC1",
    "Accounting": "#FF9AA2",
    "Software": "#C2B2DA",
    "Occupational Therapy": "#FFD1DC",
    "NON-CLASSIFIABLE": "#FFCCB6",
    "Academic Development": "#C1A3FF",
    "Dreams": "#FFB7CE",
    "Brunch": "#A0D8EF",
    "Food": "#B2A4E4",
    "18th Century": "#A8E6CF",
    "Italian": "#FFDDC1",
    "Astronomy": "#FF9AA2",
    "Psychopharmacology": "#C2B2DA",
    "Human Geography": "#FFD1DC",
    "Poultry": "#FFCCB6",
    "Container": "#C1A3FF",
    "Entomology": "#FFB7CE",
    "Modern (late 19th Century to 1945)": "#A0D8EF",
    "Number Theory": "#B2A4E4",
    "Lakes": "#A8E6CF",
    "Social Work": "#FFDDC1",
    "Lawyers & Judges": "#FF9AA2",
    "Conservatism & Liberalism": "#C2B2DA",
    "Breakfast": "#FFD1DC",
    "Woodworking": "#FFCCB6",
    "Social Classes & Economic Disparity": "#C1A3FF",
    "Wolves": "#FFB7CE",
    "Human Resources & Personnel Management": "#A0D8EF",
    "Free Will & Determinism": "#B2A4E4",
    "Annuals": "#A8E6CF",
    "Potpourri": "#FFDDC1",
    "Future Studies": "#FF9AA2",
    "Prejudice & Racism": "#C2B2DA",
    "Religious": "#FFD1DC",
    "Book": "#FFCCB6",
    "Pasta": "#C1A3FF",
    "Renaissance": "#FFB7CE",
    "Comics": "#A0D8EF",
    "Sustainable Agriculture": "#B2A4E4",
    "Social Services & Welfare": "#A8E6CF",
    "Scottish": "#FFDDC1",
    "Camping": "#FF9AA2",
    "Quizzes": "#C2B2DA",
    "Flowers & Plants": "#FFD1DC",
    "Maternity": "#FFCCB6",
    "Personal Computers": "#C1A3FF",
    "Electrical": "#FFB7CE",
    "Trial Practice": "#A0D8EF",
    "Personal Memoirs": "#B2A4E4",
    "Clip Art": "#A8E6CF",
    "Mindfulness & Meditation": "#FFDDC1",
    "Epic": "#FF9AA2",
    "Waves & Wave Mechanics": "#C2B2DA",
    "Reincarnation": "#FFD1DC",
    "Fisheries & Aquaculture": "#FFCCB6",
    "Fashion & Accessories": "#C1A3FF",
    "High Tech": "#FFB7CE",
    "Casseroles": "#A0D8EF",
    "Perennials": "#B2A4E4",
    "Computer Science": "#A8E6CF",
    "World War II": "#FFDDC1",
    "Hand Tools": "#FF9AA2",
    "Foreign Language Study": "#C2B2DA",
    "Electronic Commerce": "#FFD1DC",
    "Life Stages": "#FFCCB6",
    "Recording & Reproduction": "#C1A3FF",
    "Parent & Adult Child": "#FFB7CE",
    "Chess": "#A0D8EF",
    "Hard Science Fiction": "#A8E6CF",
    "Arithmetic": "#FFDDC1",
    "Attention Deficit Disorder (ADD-ADHD)": "#FF9AA2",
    "Central American & South American": "#C2B2DA",
    "Microwave": "#FFD1DC",
    "Feminist": "#FFCCB6",
    "Needlepoint": "#C1A3FF",
    "Local Area Networks (LANs)": "#FFB7CE",
    "Low Fat": "#A0D8EF",
    "Site Directories": "#B2A4E4",
    "Silver": "#A8E6CF",
    "Image Processing": "#FFDDC1",
    "17th Century": "#FF9AA2",
    "Horror": "#C2B2DA",
    "Digital Media": "#FFD1DC",
    "Violence": "#FFCCB6",
    "Depression": "#C1A3FF",
    "Siblings": "#FFB7CE",
    "Environmental Science": "#A0D8EF",
    "Business & Financial": "#B2A4E4",
    "Bedtime & Dreams": "#A8E6CF",
    "Young Adult Fiction": "#FFDDC1",
    "Television & Radio": "#FF9AA2",
    "Church of Jesus Christ of Latter-day Saints (Mormon)": "#C2B2DA",
    "Diets": "#FFD1DC",
    "Figurines": "#FFCCB6",
    "Atheism": "#C1A3FF",
    "Medical & Surgical": "#FFB7CE",
    "Body": "#A0D8EF",
    "Former Soviet Republics": "#B2A4E4",
    "Tigers": "#A8E6CF",
    "Short Stories (single author)": "#FFDDC1",
    "Meetings & Presentations": "#FF9AA2",
    "CAD-CAM": "#C2B2DA",
    "Southeast": "#FFD1DC",
    "Special Appliances": "#FFCCB6",
    "Surgery": "#C1A3FF",
    "Sign Language": "#FFB7CE",
    "Resumes": "#A0D8EF",
    "Native American": "#B2A4E4",
    "Developing & Emerging Countries": "#A8E6CF",
    "Interpersonal Relations": "#FFDDC1",
    "Prehistoric": "#FF9AA2",
    "Anglican": "#C2B2DA",
    "I Ching": "#FFD1DC",
    "French": "#FFCCB6",
    "Consulting": "#C1A3FF",
    "Social Media": "#FFB7CE",
    "Data Processing": "#A0D8EF",
    "Disasters": "#B2A4E4",
    "Low Salt": "#A8E6CF",
    "Fantasy": "#FFDDC1",
    "Dating": "#FF9AA2",
    "Essays & Writings": "#C2B2DA",
    "Tibetan": "#FFD1DC",
    "Industrial Health & Safety": "#FFCCB6",
    "Alternative Family": "#C1A3FF",
    "Sports": "#FFB7CE",
    "Essays": "#A0D8EF",
    "Humanistic": "#B2A4E4",
    "Speeches": "#A8E6CF",
    "Non-Euclidean": "#FFDDC1",
    "Chronic Fatigue Syndrome": "#FF9AA2",
    "Boarding School & Prep School": "#C2B2DA",
    "Humor": "#FFD1DC",
    "Ethics & Moral Philosophy": "#FFCCB6",
    "Automobile Industry": "#C1A3FF",
    "Sacred Writings": "#FFB7CE",
    "Organized Crime": "#A0D8EF",
    "Central": "#B2A4E4",
    "Nature & the Natural World": "#A8E6CF",
    "Financial Aid": "#FFDDC1",
    "Alphabet": "#FF9AA2",
    "Financial": "#C2B2DA",
    "The Message": "#FFD1DC",
    "Sounds": "#FFCCB6",
    "Labor": "#C1A3FF",
    "Flower Arranging": "#FFB7CE",
    "Genetics": "#A0D8EF",
    "Political Science": "#B2A4E4",
    "Commercial": "#A8E6CF",
    "Travel Games": "#FFDDC1",
    "the Gospels & Acts": "#FF9AA2",
    "Endocrinology & Metabolism": "#C2B2DA",
    "Science & Technology": "#FFD1DC",
    "Pediatrics": "#FFCCB6",
    "Lawns": "#C1A3FF",
    "Gifted": "#FFB7CE",
    "Women in Politics": "#A0D8EF",
    "Living Trusts": "#B2A4E4",
    "Professional Growth": "#A8E6CF",
    "Israel": "#FFDDC1",
    "Differential Equations": "#FF9AA2",
    "Speech": "#C2B2DA",
    "Topiary": "#FFD1DC",
    "Amish & Mennonite": "#FFCCB6",
    "Allergy": "#C1A3FF",
    "Reptiles": "#FFB7CE",
    "Cognitive Psychology": "#A0D8EF",
    "Skateboarding": "#B2A4E4",
    "ND": "#A8E6CF",
    "Cooking & Food": "#FFDDC1",
    "Miniatures": "#FF9AA2",
    "Benelux Countries (Belgium": "#C2B2DA",
    "Nature Crafts": "#FFD1DC",
    "Gastrointestinal": "#FFCCB6",
    "Fractions": "#C1A3FF",
    "Behavioral": "#FFB7CE",
    "Wars & Conflicts (Other)": "#A0D8EF",
    "Death & Dying": "#B2A4E4"
};

export default genreColors;