name: Deploy to Azure Web App

on:
  workflow_dispatch:
  push:
    branches:
      - 5_1_automatic_deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v2
        with:
          login-server: "rebookcontainers.azurecr.io"
          username: ${{ secrets.ACR_USERNAME   }}
          password: ${{ secrets.ACR_PASSWORD  }}

      - name: Build and Push Docker Image
        run: |
          docker build -t rebookcontainers.azurecr.io/backend:${{ github.sha }} -f backend/Dockerfile .
          docker push rebookcontainers.azurecr.io/backend:${{ github.sha }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: production
          images: 'rebookcontainers.azurecr.io/backend:${{ github.sha }}'
        env:  # Pass secrets as environment variables to the container
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
