name: Deployment of frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v2
        with:
          login-server: "rebookcontainers.azurecr.io"
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t rebookcontainers.azurecr.io/frontend:${{ github.sha }} -f frontend/Dockerfile --build-arg API_DB_URL=${{ secrets.API_DB_URL }} frontend
          docker push rebookcontainers.azurecr.io/frontend:${{ github.sha }}
        
