name: Frontend Tests

on:
  push:
    branches:
      - 15_3_frontend_tests
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    container:
      image: node:18

    services:
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size=2gb

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: |
          npm --prefix frontend run build
          npm --prefix frontend start &
      - run: npm --prefix frontend run test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: screenshots/