name: Frontend Tests

on:
  push:
    branches:
      - 15_3_frontend_tests
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify your Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm --prefix frontend install


      - name: Setup Chromedriver
        uses: nanasess/setup-chromedriver@v2
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: '88.0.4324.96'

      - name: Run Chromedriver
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      #- name: Set up ChromeDriver (part 2)
        #run: |
          #export DISPLAY=:99
          #chromedriver --url-base=/wd/hub &

        #- name: Install jest dependencies
        #run: npm --prefix frontend install --save-dev jest-environment-jsdom

      # Start the application in the background
      - name: Build application
        run: npm --prefix frontend build

      - name: Start application
        run: npm --prefix frontend start &

      # Run Selenium tests
      - name: Run tests
        run: npm --prefix frontend test
