name: Deployment of frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v2
        with:
          login-server: "rebookcontainers.azurecr.io"
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t rebookcontainers.azurecr.io/production_frontend:${{ github.sha }} -f frontend/Dockerfile --build-arg API_DB_URL=${{ secrets.PRODUCTION_API_DB_URL }} frontend
          docker push rebookcontainers.azurecr.io/production_frontend:${{ github.sha }}
          
      - name: Deploy to Azure Web App for Containers
        run: |
          az webapp config container set \
            --name ReBookWeb \
            --resource-group ReBookGroup \
            --docker-custom-image-name rebookcontainers.azurecr.io/production_frontend:${{ github.sha }} \
            --docker-registry-server-url https://rebookcontainers.azurecr.io \
            --docker-registry-server-user ${{ secrets.ACR_USERNAME }} \
            --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}
        
