name: Deployment of backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 15_4_automate_deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v2
        with:
          login-server: "rebookcontainers.azurecr.io"
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t rebookcontainers.azurecr.io/production_backend:${{ github.sha }} -f backend/Dockerfile --build-arg SUPABASE_URL=${{ secrets.PRODUCTION_SUPABASE_URL }} --build-arg SUPABASE_KEY=${{ secrets.PRODUCTION_SUPABASE_KEY }} backend
          docker push rebookcontainers.azurecr.io/production_backend:${{ github.sha }}

      - name: Deploy to Azure Web App for Containers
        run: |
          az webapp config container set \
            --name ProductionReBookBackend \
            --resource-group ReBookGroup \
            --docker-custom-image-name rebookcontainers.azurecr.io/production_backend:${{ github.sha }} \
            --docker-registry-server-url https://rebookcontainers.azurecr.io \
            --docker-registry-server-user ${{ secrets.ACR_USERNAME }} \
            --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}
        
